#pragma once

#include <cstdint>

// class Ili9341
// {
//     public:

    enum class Ili9341: uint8_t
    {
        Nop                 = 0x00,
        Rst                 = 0x01,
        ReadId              = 0x04,
        ReadSts             = 0x09,
        ReadPowerMode       = 0x0A,
        ReadMadCtl          = 0x0B,
        ReadPixelFormat     = 0x0C,
        ReadImageFormat     = 0x0D,
        ReadSignalMode      = 0x0E,
        ReadSelfDiagnostic  = 0x0F,
        EnterSleepMode      = 0x10,
        SleepOut            = 0x11,
        PartialModeOn       = 0x12,
        NormalModeOn        = 0x13,
        DisplayInversionOff = 0x20,
        DisplayInversionOn  = 0x21,
        GammaSet            = 0x26,
        DisplayOff          = 0x28,
        DisplayOn           = 0x29,
        ColumnAddressSet    = 0x2A,
        PageAddressSet      = 0x2B,
        MemoryWrite         = 0x2C,
        ColorSet            = 0x2D,
        MemoryRead          = 0x2E,
        PartialArea         = 0x30,
        VerticalScrollingDefinition = 0x33,
        TearingOff          = 0x34,
        TearingOn           = 0x35,
        MemoryAccessControl = 0x36,
        VerticalScrollingStartAddress = 0x37,
        IdleOff             = 0x38,
        IdleOn              = 0x39,
        PixelFormatSet      = 0x3A,
        WriteMemoryContinue = 0x3C,
        ReadMemoryContinue  = 0x3E,
        SetTearScanline     = 0x44,
        GetScanline         = 0x45,
        WriteBrightness     = 0x51,
        ReadBrightness      = 0x52,
        WriteCtrl           = 0x53,
        ReadCtrl            = 0x54,
        WriteContentAdaptiveBrightnessControl = 0x55,
        ReadContentAdaptiveBrightnessControl = 0x56,
        WriteCabcMinimumBrightness = 0x5E,
        ReadCabcMinimumBrightness = 0x5F,
        ReadId1             = 0xDA,
        ReadId2             = 0xDB,
        ReadId3             = 0xDC,
    // }

    // enum class CmdExt: uint8_t
    // {
        RgbInterfaceSignalControl   = 0xB0,
        FrameControlNormal          = 0xB1,
        FrameControlIdle            = 0xB2,
        FrameControlPartial         = 0xB3,
        InversionControl            = 0xB4,
        BlankingPorchControl        = 0xB5,
        FunctionControl             = 0xB6,
        EntryModeSet                = 0xB7,
        BacklightControl1           = 0xB8,
        BacklightControl2           = 0xB9,
        BacklightControl3           = 0xBA,
        BacklightControl4           = 0xBB,
        BacklightControl5           = 0xBC,
        BacklightControl6           = 0xBD,
        BacklightControl7           = 0xBE,
        BacklightControl8           = 0xBF,
        PowerControl1               = 0xC0,
        PowerControl2               = 0xC1,
        VcomControl1                = 0xC5,
        VcomControl2                = 0xC7,
        NvMemoryWrite               = 0xD0,
        NvMemoryProtectionKey       = 0xD1,
        NvMemoryStatusRead          = 0xD2,
        ReadId4                     = 0xD3,
        PositiveGammaCorrection     = 0xE0,
        NegativeGammaCorrection     = 0xE1,
        DigitalGammaControl1        = 0xE2,
        DigitalGammaControl2        = 0xE3,
        InterfaceControl            = 0xF6,
        PowerControlA               = 0xCB,
        PowerControlB               = 0xCF,
        DriverTimingControlA        = 0xE8,
        DriverTimingControlAE       = 0xE9,
        DriverTimingControlB        = 0xEA,
        PowerOnSequenceControl      = 0xED,
        Enable3G                    = 0xF2,
        PumpRatioControl            = 0xF7,
        
    }

// }